spring:
    application:
        name: CategoryProduct

    datasource:
        url: jdbc:mysql://localhost:3306/categorydb
        username: root
        password: 2002
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    cloud :
        gcp :
            project-id : springboot-app-457506
            credentials :
                location : file:/C:/Users/jatha/OneDrive/Documents/gcp/springboot-app-457506-459b9c19321c.json
#    security:
#        user:
#            name: Yogesh
#            password: 123

logging:
    file:
        name: logs/application.log
    level:
        root: INFO
        com.Rest.CategoryProduct: DEBUG