# Spring Application Name
spring:
    application:
        name: CategoryProduct

#   MySQL Database Configuration
    datasource:
        url: jdbc:mysql://localhost:3306/categorydb
        username: root
        password: 2002
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

#  GCP Cloud configuration
    cloud :
        gcp :
            project-id : springboot-app-457506
            credentials :
                location : file:/C:/Users/jatha/OneDrive/Documents/gcp/springboot-app-457506-459b9c19321c.json

#   Setting spring security default user using yaml
#    security :
#        user:
#            name: Yogesh
#            password: 123

#Logging Configuration
logging:
    level:
        root: INFO
        com.Rest.CategoryProduct: DEBUG
    file:
        name: C:\Users\jatha\Projects\CategoryProduct\CategoryProduct\logs\application.log

# Prometheus
management:
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: /actuator
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true


        enable:
            all=true:
