spring:
    application:
        name: CategoryProduct

    datasource:
        url: jdbc:mysql://localhost:3306/categorydb
        username: root
        password: 2002
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true