apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: default
type: Opaque
data:
  admin-password: YWRtaW4=  # Base64 for "admin"; change to your password (e.g., echo -n 'yourpass' | base64)
