apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: default  # Match your Prometheus namespace
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-pods'  # Existing K8s scrape (auto-discovers pods)
        kubernetes_sd_configs:
        - role: pod
      - job_name: 'categoryproduct'  # Custom job for your Spring app
        scrape_interval: 10s
        static_configs:
        - targets: ['mysqlspring-service.default.svc.cluster.local:8080']  # Service DNS: <service>.<namespace>.svc.cluster.local
        metrics_path: '/actuator/prometheus'
        scheme: http
        # Optional: Add relabeling for auth if your app requires it
